
server:
  port: 8080


spring:
  application:
    name: CUSTOMER-SERVICE


  datasource:
    url: jdbc:mysql://mysqlserver:3306/my_new_db
    username: root
    password: jaiganeshji
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
#    properties:
#      dialect: org.hibernate.dialect.MySQL8Dialect



